#!/bin/sh

mount --bind /usr/bin /workdir/usr/bin
mount --bind /bin /workdir/bin
mount --bind /dev /workdir/dev
mount --bind /proc /workdir/proc
mount --bind /sys /workdir/sys
mount --bind /lib /workdir/lib
mount --bind /usr/lib /workdir/usr/lib
chroot /workdir chroot.sh $@

